server:
  port: 7020

spring:
  application:
    name: tcp-batch
  data:
    cassandra:
      contact-points: [ "cassandra" ]
      port: 9042
      keyspace-name: monitoring
      local-datacenter: datacenter1
      schema-action: none

zookeeper:
  connect-string: localhost:2181
