server:
  port: 7010

spring:
  application:
    name: api-batch
  cassandra:
    contact-points: [ "cassandra" ]
    port: 9042
    keyspace-name: monitoring
    local-datacenter: datacenter1
    schema-action: none

zookeeper:
  connect-string: localhost:2181
